#include <string>

using namespace std;

class characterInfo {
    public:
        characterInfo();
        string getCharacterName() const;
        string getCharacterClass() const;
        int getCharacterLevel() const;
        int getProficiencyBonus() const;
        int getStrengthScore() const;
        int getDexterityScore() const;
        int getConstitutionScore() const;
        int getIntelligenceScore() const;
        int getWisdomScore() const;
        int getCharismaScore() const;
        int getStrengthModifier() const;
        int getDexterityModifier() const;
        int getConstitutionModifier() const;
        int getIntelligenceModifier() const;
        int getWisdomModifier() const;
        int getCharismaModifier() const;
        int getStrengthSave() const;
        int getDexteritySave() const;
        int getConstitutionSave() const;
        int getIntelligenceSave() const;
        int getWisdomSave() const;
        int getCharismaSave() const;
        int getAthletics() const;
        int getInitiative() const;
        int getAcrobatics() const;
        int getSleightOfHand() const;
        int getStealth() const;
        int getArcana() const;
        int getHistory() const;
        int getInvestigation() const;
        int getNature() const;
        int getReligion() const;
        int getAnimalHandling() const;
        int getInsight() const;
        int getMedicine() const;
        int getPerception() const;
        int getSurvival() const;
        int getDeception() const;
        int getIntimidation() const;
        int getPerformance() const;
        int getPersuasion() const;
        int getPassivePerception() const;
        int getPassiveInsight() const;
        int getPassiveInvestigation() const;
        void setCharacterInfo(string, string, int);
        void setAbilityScores(int, int, int, int, int, int);
        void setSavingThrows(bool, bool, bool, bool, bool, bool);
        void setStrengthSkills(int);
        void setDexteritySkills(int, int, int, int);
        void setIntelligenceSkills(int, int, int, int, int);
        void setWisdomSkills(int, int, int, int, int);
        void setCharismaSkills(int, int, int, int);

    private:
        string characterName;
        string characterClass;
        int characterLevel;
        int proficiencyBonus;
        int hitDiceCount;
        int hitDiceSize;
        int strengthScore;
        int dexterityScore;
        int constitutionScore;
        int intelligenceScore;
        int wisdomScore;
        int charismaScore;
        int strengthModifier;
        int dexterityModifier;
        int constitutionModifier;
        int intelligenceModifier;
        int wisdomModifier;
        int charismaModifier;
        int strengthSaveModifier;
        int dexteritySaveModifier;
        int constitutionSaveModifier;
        int intelligenceSaveModifier;
        int wisdomSaveModifier;
        int charismaSaveModifier;
        bool strengthSaveProficiency;
        bool dexteritySaveProficiency;
        bool constitutionSaveProficiency;
        bool intelligenceSaveProficiency;
        bool wisdomSaveProficiency;
        bool charismaSaveProficiency;
        int athleticsProf;
        int initiativeProf;
        int acrobaticsProf;
        int sleightOfHandProf;
        int stealthProf;
        int arcanaProf;
        int historyProf;
        int investigationProf;
        int natureProf;
        int religionProf;
        int animalHandlingProf;
        int insightProf;
        int medicineProf;
        int perceptionProf;
        int survivalProf;
        int deceptionProf;
        int intimidationProf;
        int performanceProf;
        int persuasionProf;
        int passivePerception;
        int passiveInsight;
        int passiveInvestigation;
};